In [41]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential

In [42]:
x = pd.read_csv('/home/beuren/Documentos/LAMIA-Bootcamp/card-14/data/classificação binária/entradas_breast.csv')
y= pd.read_csv('/home/beuren/Documentos/LAMIA-Bootcamp/card-14/data/classificação binária/saidas_breast.csv')
# carregas os dados das features e a feature target

In [43]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
# afz separação dos dados em teste e treino

In [44]:
(30 +1) /2
#faz o calculo para saber o numero ideal de neuronios na camada densa

15.5

In [64]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(30,)),
    # recebe uma tupla com o total de neuronios de entrada, 30 por onta das 30 features
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    # define a quantidade de neuronios na camada densa com funcao de ativação relu
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    # duas camadas ocultas na rede
    tf.keras.layers.Dense(units=1, activation='sigmoid')
    # escolhe a saida como 1 pois e uma classificação binaria entao usa somente uma saida com a funcao sigmoide para retornar a probabilidade
])

In [65]:
rede_neural.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [67]:
rede_neural.compile(optimizer=otimizador, loss= 'binary_crossentropy', metrics=['binary_accuracy'])
# parametros utilizados, o otimizador adam, o ajustados de pesos, e como medir os resultados do trein

In [68]:
rede_neural.fit(x_train,y_train, batch_size=10, epochs=100)
# treina o modelo com 100 registros por vez, e 100 vezes por todos os dados

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - binary_accuracy: 0.5915 - loss: 0.7753
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.6925 - loss: 0.5372
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7653 - loss: 0.4661
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7770 - loss: 0.5067
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7958 - loss: 0.6631
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7723 - loss: 0.5119
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8099 - loss: 0.4601
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8357 - loss: 0.4537
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8028 - loss: 0.4389
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8263 - loss: 0.4146
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8404 - loss: 0.4228
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8216 - loss: 0.4535
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.8685 - loss: 0.3440
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8685 - loss: 0.3741
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8545 - loss: 0.3396
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8638 - loss: 0.3532
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8451 - loss: 0.4034
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8709 - loss: 0.3403
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8638 - loss: 0.3756
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8568 - loss: 0.3863
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8474 - loss: 0.4800
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8498 - loss: 0.3611
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8779 - loss: 0.3156
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8474 - loss: 0.4151
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8873 - loss: 0.3604
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8592 - loss: 0.4231
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8427 - loss: 0.5595
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8685 - loss: 0.5267
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8662 - loss: 0.4138
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.8357 - loss: 0.5202
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8638 - loss: 0.4976
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8638 - loss: 0.4438
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8920 - loss: 0.3048
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8991 - loss: 0.3347
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8732 - loss: 0.3535
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8521 - loss: 0.3985
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8545 - loss: 0.4034
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8967 - loss: 0.2948
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8779 - loss: 0.3139
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8920 - loss: 0.3535
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8192 - loss: 0.5057
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8779 - loss: 0.3893
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8568 - loss: 0.4852
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8803 - loss: 0.4910
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8638 - loss: 0.4697
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8967 - loss: 0.4071
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8568 - loss: 0.5211
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8545 - loss: 0.4755
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8310 - loss: 0.6192
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8756 - loss: 0.4643
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8638 - loss: 0.5107
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.8662 - loss: 0.4203
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8451 - loss: 0.4335
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8685 - loss: 0.4084
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8685 - loss: 0.4002
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8779 - loss: 0.3286
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8920 - loss: 0.3433
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8732 - loss: 0.3743
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8709 - loss: 0.3900
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8545 - loss: 0.5263
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8709 - loss: 0.3986
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8310 - loss: 0.5288
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8850 - loss: 0.3461
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8310 - loss: 0.4432
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8615 - loss: 0.4565
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8756 - loss: 0.4947
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8709 - loss: 0.4264
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8732 - loss: 0.4359
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8803 - loss: 0.4331
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8826 - loss: 0.3726
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8756 - loss: 0.3650
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8709 - loss: 0.3306
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8521 - loss: 0.8884
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8732 - loss: 0.8263
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8263 - loss: 0.9470
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8310 - loss: 0.8916
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8826 - loss: 0.3487
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8803 - loss: 0.4006
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8521 - loss: 0.6610
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.8333 - loss: 0.5502
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8638 - loss: 0.4069
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8099 - loss: 0.7715
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8451 - loss: 0.5409
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8803 - loss: 0.3675
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8779 - loss: 0.4342
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8333 - loss: 0.7235
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8638 - loss: 0.4606
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8803 - loss: 0.3936
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8756 - loss: 0.4004
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8310 - loss: 0.6167
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8685 - loss: 0.4399
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8873 - loss: 0.4092
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8498 - loss: 0.4897
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.8709 - loss: 0.4493
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8732 - loss: 0.6007
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8756 - loss: 0.5023
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8873 - loss: 0.4222
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8239 - loss: 0.8912
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8850 - loss: 0.5049
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - binary_accuracy: 0.8685 - loss: 0.4597

In [49]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
30,18.63,25.11,124.80,1088.0,0.10640,0.18870,0.23190,0.124400,0.2183,0.06197,...,23.15,34.01,160.50,1670.0,0.1491,0.42570,0.61330,0.18480,0.3444,0.09782
404,12.34,14.95,78.29,469.1,0.08682,0.04571,0.02109,0.020540,0.1571,0.05708,...,13.18,16.85,84.11,533.1,0.1048,0.06744,0.04921,0.04793,0.2298,0.05974
227,15.00,15.51,97.45,684.5,0.08371,0.10960,0.06505,0.037800,0.1881,0.05907,...,16.41,19.31,114.20,808.2,0.1136,0.36270,0.34020,0.13790,0.2954,0.08362
410,11.36,17.57,72.49,399.8,0.08858,0.05313,0.02783,21.000000,0.1601,0.05913,...,13.05,36.32,85.07,521.3,0.1453,0.16220,0.18110,0.08698,0.2973,0.07745
244,19.40,23.50,129.10,1155.0,0.10270,0.15580,0.20490,0.088860,0.1978,0.06000,...,21.65,30.53,144.90,1417.0,0.1463,0.29680,0.34580,0.15640,292.0000,0.07614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,19.45,19.33,126.50,1169.0,0.10350,0.11880,0.13790,0.085910,0.1776,0.05647,...,25.70,24.57,163.10,1972.0,0.1497,0.31610,0.43170,0.19990,0.3379,0.08950
57,14.71,21.59,95.55,656.9,0.11370,0.13650,0.12930,0.081230,0.2027,0.06758,...,17.87,30.70,115.70,985.5,0.1368,429.00000,0.35870,0.18340,0.3698,0.10940
546,10.32,16.35,65.31,324.9,0.09434,0.04994,0.01012,0.005495,0.1885,0.06201,...,11.25,21.77,71.12,384.9,0.1285,0.08842,0.04384,0.02381,0.2681,0.07399
68,9029.00,17.33,58.79,250.5,0.10660,0.14130,313.00000,0.043750,0.2111,0.08046,...,10.31,22.65,65.50,324.7,0.1482,0.43650,1252.00000,175.00000,0.4228,0.11750
144,10.75,14.97,68.26,355.3,0.07793,0.05139,0.02251,0.007875,0.1399,0.05688,...,11.95,20.72,77.79,441.2,0.1076,0.12230,0.09755,0.03413,0.2300,0.06769

In [ ]:
pesos0= rede_neural.layers[0].get_weights()
# mudança de pesos da camada de entrada 30 features
pesos0

[array([[ 3.70648541e-02,  1.22211404e-01, -2.55218565e-01,
         -3.69943172e-01, -8.28907862e-02, -8.46711174e-02,
          1.12902299e-01,  4.06689942e-02,  1.04275219e-01,
          9.02481601e-02, -2.94533968e-01, -2.10844465e-02,
         -7.52122840e-03, -1.02780238e-01,  1.02157809e-01,
         -1.32440627e-01],
        [ 1.36859238e-01,  1.63741913e-02, -1.90966189e-01,
         -2.74487436e-01, -8.91388282e-02, -1.48547545e-01,
         -5.23987822e-02,  2.05940768e-01,  2.06250772e-01,
          4.75719161e-02, -9.16185305e-02, -1.50166541e-01,
          1.04916543e-02, -1.06221355e-01, -1.47390617e-02,
         -1.45766303e-01],
        [ 1.11506306e-01,  2.59112921e-02, -1.68342680e-01,
         -4.31609759e-03,  3.12858187e-02, -7.37030879e-02,
         -1.84597466e-02,  1.31738961e-01,  1.66848972e-02,
          3.86200212e-02, -1.24938883e-01,  4.54960503e-02,
          2.92734802e-02, -1.04115598e-01,  1.50414824e-01,
         -7.08307102e-02],
        [ 3.74729782e-02,  6.98593445e-04,  1.62950940e-02,
          1.12613782e-01,  3.38908620e-02,  4.09285873e-02,
         -3.16199623e-02, -6.80471286e-02,  1.41484082e-01,
         -8.76538921e-03, -4.21291124e-03,  1.95633229e-02,
          4.45792405e-03,  4.42269705e-02,  8.38141218e-02,
          2.17265356e-02],
        [-1.94981433e-02,  1.87565625e-01, -5.19687682e-02,
         -1.52293190e-01, -2.18810081e-01, -3.78223956e-01,
          2.90775727e-02, -6.49608150e-02,  1.33079603e-01,
         -4.75439541e-02, -4.76289354e-02, -1.65386453e-01,
         -1.08332805e-01, -7.18863308e-02, -1.04379235e-02,
         -1.12937339e-01],
        [-1.08789466e-01,  3.66864949e-02, -6.93053827e-02,
          6.08058050e-02,  4.29367423e-02, -1.31346539e-01,
          2.72010677e-02, -3.83240506e-02,  1.29563928e-01,
         -1.12334959e-01, -2.53877137e-03, -9.44852605e-02,
         -3.93637009e-02,  4.91683222e-02, -8.94423425e-02,
         -4.13461104e-02],
        [-9.96029601e-02,  1.68628827e-01, -8.06286111e-02,
         -1.70462608e-01, -1.36235267e-01,  2.89832591e-03,
          1.07920198e-02, -5.77885360e-02,  1.15360864e-01,
          3.72906551e-02,  2.09954709e-01, -1.47220418e-01,
          3.63832414e-02,  2.67118458e-02, -3.78046697e-03,
         -8.50753561e-02],
        [-1.88405011e-02,  6.98518679e-02,  4.21923958e-03,
         -1.84793383e-01,  2.33531743e-03,  9.40172449e-02,
          5.05930670e-02, -1.17601670e-01, -1.68496147e-01,
          1.36069417e-01,  1.62126675e-01,  2.39272729e-01,
         -9.57061946e-02,  2.67523527e-02,  1.70406848e-01,
         -7.69258067e-02],
        [ 1.25651015e-02,  2.45765243e-02, -6.24413639e-02,
          1.55045271e-01, -1.06411017e-01,  9.18302983e-02,
         -1.14870742e-02,  1.02143809e-02, -1.98180616e-01,
          2.92158909e-02, -1.03514440e-01,  1.93281978e-01,
         -1.28771767e-01, -6.75060377e-02,  3.71519215e-02,
         -3.83389108e-02],
        [ 5.78520656e-01, -4.44498032e-01, -1.38525739e-01,
          1.28886431e-01,  2.61759043e-01, -1.19611971e-01,
          1.01965614e-01,  1.14931038e-03, -9.09743831e-02,
          7.17918947e-03,  2.07315788e-01, -3.03488791e-01,
         -4.97915596e-02,  1.26324534e-01,  2.71710932e-01,
          3.07702094e-01],
        [ 5.63115068e-02, -3.58124934e-02,  1.33733705e-01,
         -2.18811065e-01, -1.86286032e-01,  4.36792895e-02,
         -8.53522271e-02,  2.33716309e-01, -2.05860677e-04,
         -1.73656836e-01, -6.74541518e-02,  7.15799406e-02,
          9.92692336e-02, -5.93407862e-02,  5.22374175e-03,
          1.25655318e-02],
        [ 1.58679131e-02,  3.30328494e-02, -8.81889388e-02,
         -1.77260444e-01,  2.39990000e-02,  4.71875945e-04,
          9.45317000e-03, -3.64530273e-03, -2.07537875e-01,
         -8.82602856e-02, -1.99540332e-03,  1.64560094e-01,
         -1.46833047e-01, -4.65772711e-02, -1.90254748e-02,
         -5.36086299e-02],
        [-1.97532540e-03,  6.50628656e-02,  7.90573377e-03,
          9.91276726e-02,  1.00198388e-02,  8.75195488e-04,
          3.09894932e-03, -3.35374065e-02,  1.13759167e-01,
          4.73995060e-02,  9.98316333e-03,  5.34229241e-02,
          2.22552605e-02, -4.58320882e-03, -3.54558527e-02,
         -2.84201521e-02],
        [-7.59479105e-02,  1.87809020e-01,  2.05137640e-01,
         -8.52894962e-01, -1.34642601e-01, -1.11720167e-01,
          1.05978459e-01,  2.05013505e-03,  5.62089086e-01,
          1.47842705e-01,  8.36300924e-02, -7.64826417e-01,
          4.13913637e-01, -7.87510648e-02, -4.48471010e-02,
         -1.21894963e-01],
        [ 4.83148806e-02, -7.30669405e-03, -2.00788319e-01,
         -1.07410111e-01, -1.30724475e-01, -3.12459946e-01,
         -2.66411100e-02,  2.17855703e-02,  7.04955980e-02,
          7.74966041e-03, -7.02844188e-02, -1.63342267e-01,
         -8.31106231e-02, -7.05629587e-02, -1.12931311e-01,
         -5.50198406e-02],
        [-6.45179212e-01,  5.46952426e-01,  1.29818451e-02,
         -7.95803308e-01, -5.38743436e-01, -1.79751307e-01,
         -1.84594214e-01,  5.31637445e-02,  4.54016060e-01,
          2.19277903e-01, -2.46555060e-01, -8.41180608e-02,
          2.55005628e-01, -3.41737062e-01, -1.40548915e-01,
         -3.91694486e-01],
        [ 5.70600852e-03,  1.93218932e-01,  3.84691060e-02,
         -1.85289919e-01, -2.00203694e-02,  1.21732011e-01,
         -3.43680196e-02,  5.38741611e-03, -9.99167003e-03,
          6.40268102e-02, -1.07664280e-01,  2.43340209e-01,
          3.25345024e-02, -6.70717657e-02,  1.50810003e-01,
          5.34994863e-02],
        [ 1.21428780e-02,  2.55944669e-01, -9.12655219e-02,
         -8.77353474e-02, -3.69853377e-02,  1.74232081e-01,
          6.69206902e-02,  3.27741764e-02, -2.10900068e-01,
          1.71631575e-01, -3.89446542e-02,  4.48559105e-01,
         -3.10409456e-01,  8.70845616e-02,  2.24016979e-01,
          1.89246401e-01],
        [ 3.86597008e-01,  2.73824543e-01, -1.18946701e-01,
          7.18258470e-02, -2.11589023e-01, -3.15814346e-01,
         -1.10496320e-01, -3.52932140e-02,  2.05015033e-01,
         -1.57603174e-01, -1.80103853e-01, -2.88435608e-01,
          9.46103036e-02, -5.67335170e-03, -2.21883208e-01,
          1.37534156e-01],
        [ 5.59735596e-02,  3.58453870e-01,  1.74956694e-01,
         -6.66524708e-01, -1.91242129e-01, -3.02785546e-01,
         -2.26266891e-01,  8.27057511e-02,  5.72713912e-01,
         -1.46883447e-03, -1.19382605e-01, -5.80237091e-01,
          1.85819104e-01, -3.35310131e-01, -1.89155400e-01,
         -1.80827975e-01],
        [ 9.25124343e-03,  1.15625806e-01, -1.72092199e-01,
         -4.88955259e-01, -6.49803653e-02, -7.39721358e-02,
          1.70360371e-01, -2.79294676e-03,  6.28861487e-02,
          1.12591714e-01, -2.36452818e-01, -9.71008763e-02,
         -3.55851799e-02, -1.06191888e-01,  6.56491192e-03,
         -1.31537706e-01],
        [ 6.92127571e-02,  4.66533490e-02, -1.70224413e-01,
         -3.83703530e-01, -1.53253078e-01, -1.40121594e-01,
         -2.77029816e-02,  2.26548940e-01,  2.24228129e-01,
          2.36136653e-02, -7.58628324e-02, -2.23807409e-01,
          1.39566630e-01, -1.33439004e-01, -3.27468105e-02,
         -2.10082829e-01],
        [ 1.48200765e-01,  1.68153755e-02, -9.22085494e-02,
         -6.86180666e-02, -6.11100383e-02, -7.58788884e-02,
         -4.78134304e-02,  7.94668123e-02,  6.76678196e-02,
          3.40781845e-02, -1.66988358e-01, -1.61438715e-02,
          4.98446599e-02, -9.35006067e-02,  7.57538974e-02,
         -1.41496614e-01],
        [-4.74124821e-03,  2.83519737e-02,  7.64345750e-02,
         -3.92217562e-03, -1.39671462e-02,  7.57406577e-02,
         -4.26482707e-02, -7.93692470e-02,  2.05120966e-01,
          3.39554809e-02, -2.60662218e-03, -1.25350043e-01,
          7.84520954e-02,  7.43499584e-03, -1.90842692e-02,
          5.65926880e-02],
        [-5.78533225e-02, -1.24565199e-01, -7.18173711e-03,
          7.62358084e-02, -2.53919840e-01, -5.27669005e-02,
          2.81471200e-02,  2.30624482e-01,  1.08614070e-02,
          9.04510617e-02,  1.02403373e-01, -1.55425956e-02,
          5.51602803e-02, -3.61229405e-02, -1.57331571e-01,
         -1.87005371e-01],
        [ 7.42708845e-03, -9.50412750e-02, -4.97070402e-02,
         -3.51326801e-02, -9.74650308e-02,  1.02506481e-01,
         -1.06716685e-01,  3.29402208e-01, -9.80819613e-02,
          1.59012660e-01, -1.85589105e-01,  1.45188242e-01,
          1.43601224e-01, -5.42013086e-02,  2.69173998e-02,
         -1.77602127e-01],
        [-8.12055618e-02, -6.39701560e-02, -2.39323936e-02,
          9.06556100e-02, -4.94236313e-02,  6.06451510e-03,
          8.71104524e-02,  5.46625927e-02, -1.51736468e-01,
          9.68643725e-02,  1.63070913e-02,  1.82589263e-01,
          2.16542155e-01, -1.27100557e-01,  5.48244105e-04,
         -2.73755461e-01],
        [ 6.62498875e-03,  4.32789251e-02,  4.51687388e-02,
         -3.32587808e-01, -1.67392232e-02, -2.24596456e-01,
          7.73638412e-02,  1.92604365e-03, -1.11372724e-01,
          3.30960043e-02,  2.88464315e-02,  4.43000868e-02,
          3.95967476e-02, -1.21439107e-01,  6.10626750e-02,
         -4.92501594e-02],
        [-4.52446379e-02, -2.23988611e-02,  1.32636338e-01,
          7.43424296e-02, -2.18366519e-01, -2.64428314e-02,
          3.55187170e-02,  8.74820352e-02, -5.62082008e-02,
         -7.00624706e-03,  1.31577170e-02,  1.00414455e-01,
          1.50304073e-02, -3.64188701e-02, -5.08520603e-02,
         -6.95076659e-02],
        [ 2.15895362e-02,  2.32332230e-01,  2.46683806e-01,
         -3.19497675e-01, -2.15779126e-01, -9.60688144e-02,
          4.10334915e-02, -2.76879948e-02,  5.67160547e-01,
         -5.41793667e-02,  1.42246455e-01, -6.89899862e-01,
          2.05064192e-01, -8.76353905e-02, -1.83140591e-01,
          2.61336304e-02]], dtype=float32),
 array([ 0.15038562, -0.17535712, -0.39635956,  0.14192206,  0.15604442,
        -0.12040431,  0.14155982,  0.06276642, -0.32782528, -0.04830337,
         0.00675318,  0.3367347 , -0.41252488,  0.00996633,  0.16156296,
         0.05155198], dtype=float32)]

In [ ]:
pesos1= rede_neural.layers[1].get_weights()
# mudança de pesos da primeira camada oculta
pesos1

[array([[-3.90933938e-02, -6.20831996e-02, -2.20105369e-02,
         -2.09090635e-02, -1.33232921e-01, -1.94349922e-02,
         -7.67910201e-03, -2.04830579e-02, -6.29473254e-02,
          2.18111739e-01, -9.19885859e-02, -1.94500268e-01,
         -2.00231984e-01, -2.89230287e-01, -1.67284742e-01,
         -4.66718301e-02],
        [-2.99111307e-02, -2.12597791e-02, -3.39068063e-02,
         -1.75206009e-02,  1.69604532e-02, -2.32468564e-02,
          3.02090924e-02, -8.94500315e-03, -1.04544751e-01,
         -2.03715488e-01, -9.86757204e-02,  1.41295686e-01,
          2.17306498e-03,  3.96895781e-02,  6.68034106e-02,
          6.20815977e-02],
        [-3.64085920e-02, -6.48454130e-02,  1.56610399e-01,
          2.03560721e-02, -2.72585824e-02,  3.98161225e-02,
         -2.67650019e-02, -6.88754767e-03,  2.61354093e-02,
          1.16668679e-01,  4.10663150e-02,  7.49806017e-02,
         -6.47885874e-02,  4.50543885e-05,  1.06037669e-02,
          1.16450280e-01],
        [-4.60749790e-02, -4.73583937e-02, -1.82973757e-01,
         -4.38318439e-02, -5.74227758e-02,  5.31163290e-02,
         -1.94262841e-03, -4.31566983e-02, -5.88335805e-02,
          1.58046067e-01, -5.96594214e-02,  8.80354196e-02,
          1.65485471e-01,  1.16084419e-01, -1.01990089e-01,
         -1.51440382e-01],
        [-3.21184322e-02, -7.13315010e-02,  3.93832177e-02,
         -6.86597079e-04, -1.37146741e-01, -4.24297787e-02,
         -4.39465716e-02, -2.27965023e-02, -2.89651584e-02,
          2.23355051e-02, -9.65833440e-02, -4.29723650e-01,
         -3.08036745e-01, -2.11883858e-02, -8.61558169e-02,
         -8.34143721e-03],
        [-8.85557104e-03,  8.80581618e-04,  1.27124950e-01,
          1.05798244e-04, -3.04141566e-02, -4.67025116e-02,
         -3.67134437e-02,  5.16670872e-04,  3.97622325e-02,
         -2.67459173e-02, -8.55931193e-02, -4.58701313e-01,
         -2.46646464e-01, -4.17099819e-02,  6.72608912e-02,
          5.83546236e-02],
        [-6.67412728e-02, -4.85115685e-02,  1.42064959e-01,
         -3.47218998e-02, -4.39214408e-02, -8.36034417e-02,
         -5.86112328e-02, -5.49165197e-02,  2.36793980e-03,
          3.74099672e-01, -9.87004340e-02, -1.97134197e-01,
         -1.85519964e-01, -1.62750930e-02, -1.83631048e-01,
          8.12110677e-03],
        [ 6.94680214e-03,  4.07840349e-02, -1.26870409e-01,
         -2.46310444e-03, -4.53773700e-02, -7.65291303e-02,
          3.16010900e-02, -5.33287749e-02,  3.65014195e-01,
         -2.35636402e-02,  3.80164683e-01, -8.94642845e-02,
         -1.70119911e-01, -1.61980599e-01, -5.58103509e-02,
          1.13941044e-01],
        [-1.57892108e-02, -2.55956352e-02,  6.70601651e-02,
         -4.77201305e-02,  6.21903278e-02, -9.12545547e-02,
         -2.93943603e-02, -3.96837741e-02, -1.35233323e-03,
          1.32653162e-01,  4.77813035e-02, -1.17533945e-01,
         -4.45446707e-02, -1.24178633e-01,  2.56022066e-02,
          1.24241985e-01],
        [ 6.57259207e-03, -3.13462541e-02,  4.71964367e-02,
         -2.73731034e-02, -1.01156421e-01, -1.98431332e-02,
         -5.27232327e-03, -4.06056363e-03,  5.33757955e-02,
         -8.94862264e-02,  1.07386913e-02,  4.99839596e-02,
         -2.25610528e-02, -4.11448404e-02,  4.26048003e-02,
         -1.50200743e-02],
        [-2.92118117e-02,  1.16681084e-02,  3.77940655e-01,
          3.36608328e-02, -4.99891974e-02, -9.77558643e-03,
          9.19719934e-02,  2.51921639e-02, -1.49890676e-01,
          4.67789844e-02, -9.71063077e-02, -1.37168750e-01,
         -1.56867579e-01,  9.83125642e-02, -2.15953261e-01,
         -9.35346633e-02],
        [-2.76252162e-02, -1.62369083e-03,  7.37937763e-02,
         -3.94715406e-02, -1.09005690e-01, -3.79097201e-02,
         -7.64503404e-02,  8.55933409e-04,  2.12758910e-02,
         -1.53501168e-01,  3.09133325e-02,  1.42191336e-01,
          9.48401019e-02,  1.02876134e-01, -1.12527288e-01,
         -1.48965210e-01],
        [-6.99852128e-03, -4.94165868e-02, -4.19017561e-02,
         -3.67297828e-02, -1.00053869e-01, -2.13582776e-02,
         -3.91556770e-02, -2.90168766e-02, -1.48936536e-03,
         -1.96044869e-03, -4.34360914e-02, -1.38321102e-01,
         -1.35878012e-01,  5.33583090e-02,  6.59911381e-03,
          2.68234983e-02],
        [-6.68053925e-02,  1.07255578e-02, -1.13572903e-01,
         -4.63955477e-03,  7.87977725e-02, -3.35853696e-02,
         -1.64521150e-02,  2.82330858e-03, -5.20405173e-02,
         -2.29498193e-01,  8.21146071e-02, -7.71556422e-02,
          1.91968381e-02,  2.56890152e-02,  6.53968453e-02,
          6.41587749e-02],
        [ 2.65445802e-02,  2.71611251e-02, -1.57863110e-01,
          6.31945580e-03,  2.23982185e-02,  2.33489200e-02,
          7.43367127e-05,  2.01519835e-03,  1.28849864e-03,
          6.14460520e-02,  1.21809905e-02, -1.51919976e-01,
          3.28801870e-02, -1.52956307e-01, -9.10196304e-02,
         -8.58194679e-02],
        [ 3.09727229e-02,  7.91399740e-03,  2.67081335e-02,
         -3.00406218e-02, -1.05951987e-01, -9.95076522e-02,
          1.97557472e-02, -6.26234934e-02, -9.90000367e-02,
          4.44241613e-02, -8.78932979e-03, -2.11174920e-01,
         -2.03783050e-01,  1.46303818e-01, -2.83338800e-02,
          9.54568535e-02]], dtype=float32),
 array([-0.03336508, -0.00625516,  0.05401975, -0.01930333, -0.1956487 ,
         0.10510534, -0.01072696, -0.01537449, -0.13587025,  0.07622354,
        -0.009037  ,  0.05987473,  0.06933676, -0.1447711 , -0.33061853,
        -0.28573972], dtype=float32)]

In [ ]:
pesos2= rede_neural.layers[2].get_weights()
# mudança de pesos da segunda camada oculta
pesos2

[array([[-0.11945869],
        [-0.12325674],
        [ 0.19976248],
        [ 0.27307498],
        [-0.30858588],
        [ 0.04509173],
        [-0.2807182 ],
        [-0.20600328],
        [-0.25348783],
        [ 0.32314742],
        [-0.3064359 ],
        [ 0.07628644],
        [ 0.03576559],
        [ 0.24363287],
        [-0.74752206],
        [-0.37781477]], dtype=float32),
 array([0.07582486], dtype=float32)]

In [73]:
len(pesos0)

2

In [69]:
previsoes = rede_neural.predict(x_test)
previsoes= previsoes >0.5
# faz a predicao com os dados de teste e coloca uma condição para numeros acima de 0.5 True e abaixo False

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

In [53]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

In [54]:
y_test

     0
30   0
404  1
227  1
410  1
244  0
..  ..
254  0
57   0
546  1
68   1
144  1

[143 rows x 1 columns]

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [70]:
accuracy_score(y_test, previsoes)
# compara os dados reais com as previsoes do modelo

0.8181818181818182

In [71]:
confusion_matrix(y_test, previsoes)

# matriz de confusao, 12 dados que eram benignos ele marcou como maligno e 2 malignos como benignos

array([[43, 16],
       [10, 74]])

In [ ]:
47 + 82, 12+2
# verificando as metricas da matriz

(129, 14)

In [62]:
129/143, 14/143

(0.9020979020979021, 0.0979020979020979)

In [ ]:
rede_neural.evaluate(x_test, y_test)
# confirmando a acuracia e o loss

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - binary_accuracy: 0.9021 - loss: 0.5570

[0.5570301413536072, 0.9020978808403015]