In [51]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense, Activation, Input
from tensorflow.keras.models import Model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error

In [ ]:
student_performance = fetch_ucirepo(id=320)
# carrego os dados do dataset
x = student_performance.data.features
y = student_performance.data.targets
# objetivo é prever 3 saidas, 1 nota para 3 periodos difrentes

In [53]:
x

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,4
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,2
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,6
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,yes,yes,no,5,4,2,1,2,5,4
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,yes,yes,no,4,3,4,1,1,1,4
646,MS,F,18,U,GT3,T,1,1,other,other,...,yes,no,no,1,1,1,1,1,5,6
647,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,6
648,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,4

In [54]:
y

     G1  G2  G3
0     0  11  11
1     9  11  11
2    12  13  12
3    14  14  14
4    11  13  13
..   ..  ..  ..
644  10  11  10
645  15  15  16
646  11  12   9
647  10  10  10
648  10  11  11

[649 rows x 3 columns]

In [ ]:
y1 = y.iloc[:,0]
y2 = y.iloc[:,1]
y3 = y.iloc[:,2]
# separo as 3 colunas target

In [56]:
x.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
dtype: object

In [ ]:
x = x.drop('address', axis = 1)
# retiro o endereço, por mais que possa ajudar na previsao

In [ ]:
sum =x.select_dtypes(include='object').columns
#soma da quantidade de colunas do tipo objeto

In [ ]:
Oh = ColumnTransformer(transformers=[('OneHot',OneHotEncoder(),sum)], remainder='passthrough')
# crio o one hot encoder para fazer a transformação das colunas categoricas
x = Oh.fit_transform(x)

In [ ]:
x.shape
# dimensao

(649, 54)

In [61]:
(54+3) /2

28.5

In [ ]:
cInput = Input(shape=(54,))
oculta1 = Dense(units=28, activation='relu')(cInput)
oculta2 = Dense(units=28, activation='relu')(oculta1)
saida1= Dense(units=1,activation='linear')(oculta2)
saida2= Dense(units=1,activation='linear')(oculta2)
saida3= Dense(units=1,activation='linear')(oculta2)
# mesmo estilo de 1 saida, porem agora com 3 saidas
# cada uma se referencia a outra, pega a camada anterior, como os outputs sao os ultimo a camada oculta2 é de onde vai saiir as 3 previsoes

In [ ]:
regressao = Model(inputs= cInput,outputs=[saida1,saida2,saida3])
# atribui ao mudelo os inputs e as 3 saidas
regressao.compile(optimizer='adam', loss = 'mse')

In [ ]:
regressao.fit(x, [y1, y2, y3], epochs=500, batch_size=100)
# treina o modelo

Epoch 1/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - dense_12_loss: 57.9785 - dense_13_loss: 149.2932 - dense_14_loss: 120.5199 - loss: 329.4557
Epoch 2/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 38.3730 - dense_13_loss: 125.0407 - dense_14_loss: 89.9179 - loss: 256.0551
Epoch 3/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 22.7179 - dense_13_loss: 101.7585 - dense_14_loss: 60.3113 - loss: 186.7466
Epoch 4/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 13.1096 - dense_13_loss: 76.1347 - dense_14_loss: 34.6199 - loss: 125.8852
Epoch 5/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 10.7788 - dense_13_loss: 50.9765 - dense_14_loss: 18.3753 - loss: 81.4737
Epoch 6/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 12.1169 - dense_13_loss: 29.0844 - dense_14_loss: 14.6227 - loss: 55.9858
Epoch 7/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 11.7506 - dense_13_loss: 15.3019 - dense_14_loss: 15.6227 - loss: 42.9604
Epoch 8/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 10.1774 - dense_13_loss: 10.6657 - dense_14_loss: 15.6273 - loss: 36.7380
Epoch 9/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 9.7372 - dense_13_loss: 9.9967 - dense_14_loss: 14.1170 - loss: 33.6091
Epoch 10/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 9.3053 - dense_13_loss: 9.7630 - dense_14_loss: 12.8393 - loss: 31.9564
Epoch 11/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 9.1829 - dense_13_loss: 9.3834 - dense_14_loss: 12.3517 - loss: 31.2107
Epoch 12/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 9.0738 - dense_13_loss: 9.4593 - dense_14_loss: 12.8662 - loss: 30.6085
Epoch 13/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 8.7946 - dense_13_loss: 8.8964 - dense_14_loss: 11.9611 - loss: 29.9241
Epoch 14/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 8.7612 - dense_13_loss: 8.9074 - dense_14_loss: 11.6506 - loss: 29.2624
Epoch 15/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 8.4063 - dense_13_loss: 8.6771 - dense_14_loss: 11.5549 - loss: 28.8206
Epoch 16/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 8.1282 - dense_13_loss: 8.6709 - dense_14_loss: 11.6563 - loss: 28.3789
Epoch 17/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 8.0845 - dense_13_loss: 8.3995 - dense_14_loss: 11.3403 - loss: 27.8702
Epoch 18/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 7.9317 - dense_13_loss: 8.0857 - dense_14_loss: 10.7907 - loss: 27.4351
Epoch 19/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 7.8905 - dense_13_loss: 8.3481 - dense_14_loss: 10.8299 - loss: 27.0614
Epoch 20/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 7.7225 - dense_13_loss: 8.5025 - dense_14_loss: 11.0181 - loss: 26.6023
Epoch 21/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - dense_12_loss: 7.9917 - dense_13_loss: 8.1517 - dense_14_loss: 11.0122 - loss: 26.2503
Epoch 22/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 7.5715 - dense_13_loss: 8.1038 - dense_14_loss: 10.4969 - loss: 25.8922
Epoch 23/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 7.4948 - dense_13_loss: 8.0741 - dense_14_loss: 10.7170 - loss: 25.4748
Epoch 24/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 7.2808 - dense_13_loss: 8.0037 - dense_14_loss: 10.3961 - loss: 25.1596
Epoch 25/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - dense_12_loss: 7.0470 - dense_13_loss: 7.6225 - dense_14_loss: 10.0132 - loss: 24.7934
Epoch 26/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 7.0090 - dense_13_loss: 7.4818 - dense_14_loss: 9.8511 - loss: 24.4527
Epoch 27/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 7.2598 - dense_13_loss: 7.4580 - dense_14_loss: 9.7406 - loss: 24.1308
Epoch 28/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 6.8031 - dense_13_loss: 7.2051 - dense_14_loss: 9.3016 - loss: 23.8172
Epoch 29/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 6.7904 - dense_13_loss: 7.3102 - dense_14_loss: 9.6036 - loss: 23.5197
Epoch 30/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 6.6005 - dense_13_loss: 7.0828 - dense_14_loss: 9.3113 - loss: 23.2216
Epoch 31/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 6.6575 - dense_13_loss: 7.4588 - dense_14_loss: 9.5221 - loss: 22.9291
Epoch 32/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 6.3921 - dense_13_loss: 6.9617 - dense_14_loss: 8.8934 - loss: 22.6903
Epoch 33/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 6.3930 - dense_13_loss: 7.1935 - dense_14_loss: 9.3274 - loss: 22.3819
Epoch 34/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 6.3827 - dense_13_loss: 6.8949 - dense_14_loss: 9.1732 - loss: 22.1177
Epoch 35/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 6.1773 - dense_13_loss: 6.7119 - dense_14_loss: 8.5327 - loss: 21.8580
Epoch 36/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 6.1566 - dense_13_loss: 6.7392 - dense_14_loss: 8.7301 - loss: 21.6267
Epoch 37/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 6.1593 - dense_13_loss: 6.9254 - dense_14_loss: 9.0193 - loss: 21.3314
Epoch 38/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 6.0690 - dense_13_loss: 6.8794 - dense_14_loss: 8.6018 - loss: 21.1300
Epoch 39/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 6.1078 - dense_13_loss: 6.6950 - dense_14_loss: 8.4115 - loss: 20.9410
Epoch 40/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.9724 - dense_13_loss: 6.4995 - dense_14_loss: 8.1037 - loss: 20.7255
Epoch 41/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.7660 - dense_13_loss: 6.3731 - dense_14_loss: 7.9691 - loss: 20.6002
Epoch 42/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - dense_12_loss: 5.6806 - dense_13_loss: 6.2904 - dense_14_loss: 7.8988 - loss: 20.3953
Epoch 43/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 5.7085 - dense_13_loss: 6.3483 - dense_14_loss: 8.2207 - loss: 20.2414
Epoch 44/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.8469 - dense_13_loss: 6.4703 - dense_14_loss: 8.2139 - loss: 20.0875
Epoch 45/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.6366 - dense_13_loss: 6.2499 - dense_14_loss: 7.7994 - loss: 20.0086
Epoch 46/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.6177 - dense_13_loss: 6.1285 - dense_14_loss: 7.6419 - loss: 19.8426
Epoch 47/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.5840 - dense_13_loss: 6.3287 - dense_14_loss: 7.8161 - loss: 19.7040
Epoch 48/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.4557 - dense_13_loss: 6.1735 - dense_14_loss: 7.6227 - loss: 19.5752
Epoch 49/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.7250 - dense_13_loss: 6.3047 - dense_14_loss: 7.6787 - loss: 19.5949
Epoch 50/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.5519 - dense_13_loss: 6.2773 - dense_14_loss: 7.8346 - loss: 19.3885
Epoch 51/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.6088 - dense_13_loss: 6.2714 - dense_14_loss: 7.6490 - loss: 19.3033
Epoch 52/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.5006 - dense_13_loss: 6.2154 - dense_14_loss: 7.8988 - loss: 19.2121
Epoch 53/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.4769 - dense_13_loss: 6.0595 - dense_14_loss: 7.4160 - loss: 19.1508
Epoch 54/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.3960 - dense_13_loss: 6.1645 - dense_14_loss: 7.7558 - loss: 19.0255
Epoch 55/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.4136 - dense_13_loss: 6.1781 - dense_14_loss: 7.4648 - loss: 19.0075
Epoch 56/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.3080 - dense_13_loss: 6.0152 - dense_14_loss: 7.3688 - loss: 18.9011
Epoch 57/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.3667 - dense_13_loss: 5.9970 - dense_14_loss: 7.5008 - loss: 18.8294
Epoch 58/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.3651 - dense_13_loss: 5.9571 - dense_14_loss: 7.2443 - loss: 18.7525
Epoch 59/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.4639 - dense_13_loss: 6.1143 - dense_14_loss: 7.5899 - loss: 18.7053
Epoch 60/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.5405 - dense_13_loss: 6.0833 - dense_14_loss: 7.3073 - loss: 18.6312
Epoch 61/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.2147 - dense_13_loss: 5.8670 - dense_14_loss: 7.2415 - loss: 18.5767
Epoch 62/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.5664 - dense_13_loss: 5.8429 - dense_14_loss: 7.0222 - loss: 18.5445
Epoch 63/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.2333 - dense_13_loss: 5.7746 - dense_14_loss: 7.1396 - loss: 18.5534
Epoch 64/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.6297 - dense_13_loss: 6.0837 - dense_14_loss: 7.4574 - loss: 18.5556
Epoch 65/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.3163 - dense_13_loss: 5.9081 - dense_14_loss: 7.1850 - loss: 18.2662
Epoch 66/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.3936 - dense_13_loss: 5.9401 - dense_14_loss: 7.3251 - loss: 18.7296
Epoch 67/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.2813 - dense_13_loss: 5.8197 - dense_14_loss: 7.0187 - loss: 18.3865
Epoch 68/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.2182 - dense_13_loss: 5.7178 - dense_14_loss: 6.9680 - loss: 18.3706
Epoch 69/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.1887 - dense_13_loss: 5.8325 - dense_14_loss: 7.0839 - loss: 18.2565
Epoch 70/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.2487 - dense_13_loss: 5.9152 - dense_14_loss: 7.4588 - loss: 18.3275
Epoch 71/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.0662 - dense_13_loss: 5.8102 - dense_14_loss: 6.9186 - loss: 18.1242
Epoch 72/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.3249 - dense_13_loss: 6.0897 - dense_14_loss: 7.1821 - loss: 18.1111
Epoch 73/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.1375 - dense_13_loss: 5.7258 - dense_14_loss: 6.9954 - loss: 18.0893
Epoch 74/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.3098 - dense_13_loss: 6.1318 - dense_14_loss: 7.3210 - loss: 18.0022
Epoch 75/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.1288 - dense_13_loss: 5.8359 - dense_14_loss: 7.1598 - loss: 17.9785
Epoch 76/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.1157 - dense_13_loss: 5.7521 - dense_14_loss: 7.0162 - loss: 17.9768
Epoch 77/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.1164 - dense_13_loss: 5.8356 - dense_14_loss: 6.9975 - loss: 18.0044
Epoch 78/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.1209 - dense_13_loss: 5.6543 - dense_14_loss: 6.7574 - loss: 17.9230
Epoch 79/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.3606 - dense_13_loss: 5.7089 - dense_14_loss: 6.8732 - loss: 17.8468
Epoch 80/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.1672 - dense_13_loss: 5.8827 - dense_14_loss: 7.0125 - loss: 17.8584
Epoch 81/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.1618 - dense_13_loss: 5.6851 - dense_14_loss: 6.8476 - loss: 17.9527
Epoch 82/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.0186 - dense_13_loss: 5.6306 - dense_14_loss: 6.7906 - loss: 17.7892
Epoch 83/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.0682 - dense_13_loss: 5.7792 - dense_14_loss: 7.2555 - loss: 17.7839
Epoch 84/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.1158 - dense_13_loss: 5.9225 - dense_14_loss: 7.1242 - loss: 17.7422
Epoch 85/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.1385 - dense_13_loss: 5.8671 - dense_14_loss: 7.1600 - loss: 17.6783
Epoch 86/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.1287 - dense_13_loss: 5.7712 - dense_14_loss: 6.8430 - loss: 17.8402
Epoch 87/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.9987 - dense_13_loss: 5.7053 - dense_14_loss: 6.7968 - loss: 17.6220
Epoch 88/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.0235 - dense_13_loss: 5.6613 - dense_14_loss: 6.7997 - loss: 17.7357
Epoch 89/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 5.0135 - dense_13_loss: 5.6020 - dense_14_loss: 6.7493 - loss: 17.5966
Epoch 90/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 4.9878 - dense_13_loss: 5.5126 - dense_14_loss: 6.6229 - loss: 17.5289
Epoch 91/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.0397 - dense_13_loss: 5.6553 - dense_14_loss: 7.1537 - loss: 17.5447
Epoch 92/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.1002 - dense_13_loss: 5.6744 - dense_14_loss: 6.8395 - loss: 17.5892
Epoch 93/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 4.9608 - dense_13_loss: 5.6236 - dense_14_loss: 6.7778 - loss: 17.4800
Epoch 94/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.2529 - dense_13_loss: 5.6288 - dense_14_loss: 6.8604 - loss: 17.4732
Epoch 95/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.1281 - dense_13_loss: 5.6268 - dense_14_loss: 6.8061 - loss: 17.4602
Epoch 96/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.0055 - dense_13_loss: 5.5901 - dense_14_loss: 6.7322 - loss: 17.4158
Epoch 97/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 5.1263 - dense_13_loss: 5.5883 - dense_14_loss: 6.6335 - loss: 17.4074
Epoch 98/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.9051 - dense_13_loss: 5.5772 - dense_14_loss: 6.9423 - loss: 17.4120
Epoch 99/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 4.9375 - dense_13_loss: 5.6185 - dense_14_loss: 6.8324 - loss: 17.3733
Epoch 100/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.9097 - dense_13_loss: 5.4753 - dense_14_loss: 6.6114 - loss: 17.3598
Epoch 101/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 4.9916 - dense_13_loss: 5.5378 - dense_14_loss: 6.9699 - loss: 17.3271
Epoch 102/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 4.9292 - dense_13_loss: 5.4107 - dense_14_loss: 6.5680 - loss: 17.3209
Epoch 103/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.0084 - dense_13_loss: 5.7802 - dense_14_loss: 6.8559 - loss: 17.4272
Epoch 104/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 5.0506 - dense_13_loss: 5.6558 - dense_14_loss: 6.8237 - loss: 17.4158
Epoch 105/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - dense_12_loss: 5.0603 - dense_13_loss: 5.6017 - dense_14_loss: 6.7041 - loss: 17.3629
Epoch 106/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 5.2943 - dense_13_loss: 5.5339 - dense_14_loss: 6.7496 - loss: 17.2605
Epoch 107/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 5.0538 - dense_13_loss: 5.8969 - dense_14_loss: 7.0271 - loss: 17.3114
Epoch 108/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.9554 - dense_13_loss: 5.4080 - dense_14_loss: 6.5230 - loss: 17.2496
Epoch 109/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 4.9416 - dense_13_loss: 5.6250 - dense_14_loss: 6.9061 - loss: 17.2096
Epoch 110/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.9555 - dense_13_loss: 5.4697 - dense_14_loss: 6.5954 - loss: 17.2120
Epoch 111/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.9138 - dense_13_loss: 5.4529 - dense_14_loss: 6.6137 - loss: 17.1742
Epoch 112/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 5.0625 - dense_13_loss: 5.5083 - dense_14_loss: 6.6257 - loss: 17.1358
Epoch 113/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 4.9436 - dense_13_loss: 5.5710 - dense_14_loss: 6.6672 - loss: 17.1246
Epoch 114/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 4.8697 - dense_13_loss: 5.6074 - dense_14_loss: 6.6761 - loss: 17.1420
Epoch 115/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.7756 - dense_13_loss: 5.3566 - dense_14_loss: 6.4399 - loss: 17.0962
Epoch 116/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.8741 - dense_13_loss: 5.4008 - dense_14_loss: 6.4718 - loss: 17.1165
Epoch 117/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 4.9882 - dense_13_loss: 5.5603 - dense_14_loss: 6.8515 - loss: 17.2588
Epoch 118/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 5.0754 - dense_13_loss: 5.3792 - dense_14_loss: 6.5009 - loss: 17.0934
Epoch 119/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.8000 - dense_13_loss: 5.4814 - dense_14_loss: 6.4788 - loss: 17.0580
Epoch 120/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 4.8577 - dense_13_loss: 5.5953 - dense_14_loss: 6.6733 - loss: 17.0364
Epoch 121/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 4.7415 - dense_13_loss: 5.3577 - dense_14_loss: 6.5664 - loss: 17.0014
Epoch 122/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.8719 - dense_13_loss: 5.6272 - dense_14_loss: 6.7163 - loss: 17.0267
Epoch 123/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 4.8549 - dense_13_loss: 5.3740 - dense_14_loss: 6.6479 - loss: 17.0068
Epoch 124/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 4.8393 - dense_13_loss: 5.3957 - dense_14_loss: 6.5576 - loss: 17.0448
Epoch 125/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 4.8434 - dense_13_loss: 5.3299 - dense_14_loss: 6.4671 - loss: 17.0841
Epoch 126/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 4.8608 - dense_13_loss: 5.4259 - dense_14_loss: 6.4494 - loss: 17.1750
Epoch 127/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - dense_12_loss: 5.0047 - dense_13_loss: 5.2640 - dense_14_loss: 6.3158 - loss: 16.9247
Epoch 128/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.8011 - dense_13_loss: 5.4133 - dense_14_loss: 6.6376 - loss: 16.9807
Epoch 129/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - dense_12_loss: 4.8409 - dense_13_loss: 5.5305 - dense_14_loss: 6.5793 - loss: 16.9840
Epoch 130/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.8667 - dense_13_loss: 5.4732 - dense_14_loss: 6.6554 - loss: 16.9307
Epoch 131/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.9675 - dense_13_loss: 5.4703 - dense_14_loss: 6.5073 - loss: 17.0637
Epoch 132/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.8701 - dense_13_loss: 5.5691 - dense_14_loss: 6.6961 - loss: 16.8748
Epoch 133/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - dense_12_loss: 4.7939 - dense_13_loss: 5.3889 - dense_14_loss: 6.5676 - loss: 16.8354
Epoch 134/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - dense_12_loss: 4.8384 - dense_13_loss: 5.4633 - dense_14_loss: 6.5642 - loss: 16.9114
Epoch 135/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.6928 - dense_13_loss: 5.2831 - dense_14_loss: 6.3810 - loss: 16.8241
Epoch 136/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - dense_12_loss: 4.9812 - dense_13_loss: 5.3291 - dense_14_loss: 6.5017 - loss: 16.8409
Epoch 137/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.7205 - dense_13_loss: 5.4246 - dense_14_loss: 6.5096 - loss: 16.8023
Epoch 138/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.8033 - dense_13_loss: 5.4181 - dense_14_loss: 6.6075 - loss: 16.8330
Epoch 139/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - dense_12_loss: 4.7209 - dense_13_loss: 5.3030 - dense_14_loss: 6.3306 - loss: 16.7708
Epoch 140/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - dense_12_loss: 4.7692 - dense_13_loss: 5.3573 - dense_14_loss: 6.3412 - loss: 16.7495
Epoch 141/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.7331 - dense_13_loss: 5.3016 - dense_14_loss: 6.3457 - loss: 16.7911
Epoch 142/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - dense_12_loss: 4.8651 - dense_13_loss: 5.5044 - dense_14_loss: 6.5640 - loss: 16.8798
Epoch 143/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - dense_12_loss: 4.7348 - dense_13_loss: 5.2997 - dense_14_loss: 6.3563 - loss: 16.7411
Epoch 144/500

In [ ]:
predict1,predict2,predict3 = regressao.predict(x)
# faz a predição para as tres saidas

21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [73]:
y1.mean(),y2.mean(), y3.mean()
# media das 3 notas

(np.float64(11.399075500770415),
 np.float64(11.570107858243452),
 np.float64(11.906009244992296))

In [ ]:
predict1.mean(),predict2.mean(), predict3.mean()
# media das predições

(np.float32(11.119502), np.float32(11.2808075), np.float32(11.581188))

In [74]:
mean_absolute_error(y1,predict1),mean_absolute_error(y2,predict2),mean_absolute_error(y3,predict2)
#calcula os 3 MAE

(np.float64(1.3714895388011021),
 np.float64(1.4268994647292033),
 np.float64(1.612679437422789))